name: workspace
organization: my_organization
description: Lakehouse - Workspace Configuration
backend: terraform
resources:
  databricks_directories: ${include.resources/directories.yaml}
  databricks_warehouses: ${include.resources/warehouses.yaml}
  providers:
    databricks:
      host: ${vars.DATABRICKS_HOST}
      token: ${vars.DATABRICKS_TOKEN}
environments:
  dev:
    variables:
      env: dev
  prd:
    variables:
      env: prd
