# GENERATED FILE - DO NOT EDIT
# Regenerate with: python scripts/build_resources/01_build.py databricks_budget_policy
from __future__ import annotations

from pydantic import Field

from laktory.models.basemodel import BaseModel
from laktory.models.resources.terraformresource import TerraformResource


class BudgetPolicyCustomTags(BaseModel):
    key: str = Field(
        ...,
        description="The key of the tag. - Must be unique among all custom tags of the same policy - Cannot be “budget-policy-name”, “budget-policy-id” or 'budget-policy-resolution-result' - these tags are preserved",
    )
    value: str | None = Field(None, description="The value of the tag")


class BudgetPolicyBase(BaseModel, TerraformResource):
    """
    Generated base class for `databricks_budget_policy`.
    DO NOT EDIT - regenerate from `scripts/build_resources/01_build.py`.
    """

    __doc_generated_base__ = True

    binding_workspace_ids: list[int] | None = Field(
        None,
        description="List of workspaces that this budget policy will be exclusively bound to. An empty binding implies that this budget policy is open to any workspace in the account",
    )
    policy_id: str | None = Field(
        None,
        description="The Id of the policy. This field is generated by Databricks and globally unique",
    )
    policy_name: str | None = Field(
        None,
        description="The name of the policy. - Must be unique among active policies. - Can contain only characters from the ISO 8859-1 (latin1) set. - Can't start with reserved keywords such as `databricks:default-policy`",
    )
    custom_tags: list[BudgetPolicyCustomTags] | None = Field(
        None,
        description="A list of tags defined by the customer. At most 20 entries are allowed per policy",
    )

    @property
    def terraform_resource_type(self) -> str:
        return "databricks_budget_policy"


__all__ = ["BudgetPolicyBase", "BudgetPolicyCustomTags"]
