from laktory.models.basemodel import PluralField
from laktory.models.resources.databricks.accesscontrol import AccessControl
from laktory.models.resources.databricks.permissions_base import *  # NOQA: F403 required for documentation
from laktory.models.resources.databricks.permissions_base import PermissionsBase


class Permissions(PermissionsBase):
    """
    Databricks Permissions

    This resource is typically auto-generated by Laktory when you set
    `access_controls` on resources like `Cluster`, `Job`, `Notebook`, etc.
    It can also be configured manually when fine-grained control is needed.

    Examples
    --------
    ```py
    import io

    from laktory import models

    perms_yaml = '''
    cluster_id: ${resources.cluster-default.id}
    access_controls:
    - group_name: role-engineers
      permission_level: CAN_RESTART
    - group_name: account users
      permission_level: CAN_ATTACH_TO
    '''
    perms = models.resources.databricks.Permissions.model_validate_yaml(
        io.StringIO(perms_yaml)
    )
    ```

    References
    ----------

    * [Databricks Permissions](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/permissions)
    """

    access_control: list[AccessControl] = PluralField(
        ...,
        description="Access controls list",
    )
