from typing import Callable

from pydantic import Field
from pydantic import computed_field

from laktory._logger import get_logger
from laktory.models.basemodel import BaseModel
from laktory.models.basemodel import PluralField
from laktory.models.resources.databricks.accesscontrol import AccessControl
from laktory.models.resources.terraformresource import TerraformResource

logger = get_logger(__name__)


class PythonPackagePermissions(BaseModel, TerraformResource):
    """
    Permissions resource auto-generated by a `PythonPackage` resource when
    `access_controls` are defined. Not intended for direct instantiation.
    """

    access_control: list[AccessControl] = PluralField(
        ...,
        description="Access controls list",
    )
    get_workspace_file_path: Callable = Field(
        ..., description="Callable returning workspace filepath", exclude=True
    )

    @computed_field(description="workspace_file_path")
    @property
    def workspace_file_path(self) -> str:
        return self.get_workspace_file_path()

    # ----------------------------------------------------------------------- #
    # Terraform Properties                                                    #
    # ----------------------------------------------------------------------- #

    @property
    def terraform_resource_type(self) -> str:
        return "databricks_permissions"
