from pathlib import Path

from pydantic import Field
from pydantic import computed_field

from laktory._logger import get_logger
from laktory._settings import settings
from laktory.models.pipelinechild import PipelineChild
from laktory.models.resources.databricks.accesscontrol import AccessControl
from laktory.models.resources.databricks.workspacefile import WorkspaceFile

logger = get_logger(__name__)


class SqlExecutionWorkspaceFile(WorkspaceFile, PipelineChild):
    """
    Workspace file containing the SQL statements for one pipeline execution
    task. Generated by DatabricksJobOrchestrator when warehouse_id is set.
    One file is produced per execution task (group of nodes).
    """

    task_name: str = Field(..., description="Execution task key this SQL file covers")
    access_controls: list[AccessControl] = [
        AccessControl(permission_level="CAN_READ", group_name="users")
    ]

    @computed_field(description="source")
    @property
    def source(self) -> str | None:
        pl_name = ""
        try:
            pl = self.parent_pipeline
            if pl is not None:
                pl_name = pl.name
        except ImportError:
            pass
        source_path = (
            Path(settings.build_root) / "pipelines" / f"{pl_name}.{self.task_name}.sql"
        )
        return str(source_path)

    @computed_field(description="path")
    @property
    def path(self) -> str | None:
        if self.path_:
            return self.path_
        pl = self.parent_pipeline
        if not pl:
            return None
        return f"{settings.workspace_root}pipelines/{pl.name}.{self.task_name}.sql"

    @property
    def sql_statements(self) -> list[str]:
        """Generate SQL statements for all nodes in this task."""
        pl = self.parent_pipeline
        plan = pl.get_execution_plan()
        pl_task = plan.tasks_dict[self.task_name]

        statements = []
        for node_name in pl_task.node_names:
            node = pl.nodes_dict[node_name]
            statements.extend(node.sql_statements)
        return statements

    def build(self):
        """Write SQL statements to the build root file."""
        filepath = Path(self.source)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        content = ";\n\n".join(self.sql_statements) + ";"
        logger.debug(f"Writing SQL execution file at {filepath}")
        with filepath.open("w") as fp:
            fp.write(content)

    # ----------------------------------------------------------------------- #
    # Resource Properties                                                     #
    # ----------------------------------------------------------------------- #

    @property
    def terraform_excludes(self) -> list[str] | dict[str, bool]:
        return super().terraform_excludes + [
            "task_name",
            "dataframe_backend",
            "dataframe_api",
        ]

    @property
    def resource_type_id(self) -> str:
        return "workspace-file"
