name: account
description: Lakehouse - Account Configuration
backend: terraform

# List of Resources to deploy
resources:

  # Account Groups
  databricks_groups: ${include.resources/groups.yaml}

  # Account Users
  databricks_users: ${include.resources/users.yaml}

  # Databricks Provider Configuration
  providers:
    databricks:
      host: https://accounts.azuredatabricks.net
      account_id: ${vars.DATABRICKS_ACCOUNT_ID}
      azure_tenant_id: ${vars.AZURE_TENANT_ID}
      azure_client_id: ${vars.AZURE_CLIENT_ID}
      azure_client_secret: ${vars.AZURE_CLIENT_SECRET}
#    databricks.workspace-dev:
#      alias: workspace-dev
#      host: ${vars.DATABRICKS_HOST}
#      token: ${vars.DATABRICKS_TOKEN}

variables:
  sp_client_id_dev: 1
  sp_client_id_prd: 2
  sp_client_secret_dev: 3
  sp_client_secret_prd: 4
  workspace_id_dev: 2211091707396001  # TODO: CUSTOMIZE WITH YOUR WORKSPACE ID
