name: publish-doc

on:
  workflow_dispatch:
    logLevel:
      description: 'Log level'
      default: 'info'

jobs:
  doc:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.14"

      - name: Publish doc
        run: |
          uv venv
          source .venv/bin/activate
          make publishdoc
