name: run-quickstart

on:
  workflow_call:
    inputs:
      cwd:
        type: string
        description: 'Working Directory'
        required: true
      template:
        type: string
        description: 'Quickstart Template'
        required: true
      action:
        type: string
        description: 'Action to perform: deploy | destroy | run-job | run-dlt'
        required: true
      resource_name:
        type: string
        description: 'Job or pipeline name (for run-job and run-dlt actions)'
        default: ''

env:
  LAKTORY_CLI_RAISE_EXTERNAL_EXCEPTIONS: "true"

  # UC Only
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  DATABRICKS_ACCOUNT_ID: ${{ secrets.DATABRICKS_ACCOUNT_ID }}
  # All
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  CWD: ${{ inputs.cwd }}

jobs:
  laktory-quickstart:
    runs-on: ubuntu-22.04  # ubuntu-latest does not seem to have terraform available anymore
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.14"
          python-version: "3.12"

      - name: env vars
        run: |
          import os
          for k, v in os.environ.items():
            print(k, "|", v)
        shell: python

      - name: Install Laktory
        run: |
          make install-with-dbks

      - name: make dir
        run: |
          mkdir -p ${{ env.CWD }}

      - name: run quickstart
        run: |
          source ../.venv/bin/activate
          laktory quickstart -t ${{ inputs.template }}
        working-directory: ${{ env.CWD }}

      - name: update stack
        run: |
          source ../.venv/bin/activate
          python ../.github/scripts/update_quickstart_stack.py ${{ github.ref }} ${{ inputs.template }}
        working-directory: ${{ env.CWD }}

      - name: laktory init
        if: ${{ inputs.action == 'deploy' || inputs.action == 'destroy' }}
        run: |
          source ../.venv/bin/activate
          laktory init --options -reconfigure
        working-directory: ${{ env.CWD }}

      - name: laktory preview
        if: ${{ inputs.action == 'deploy' }}
        run: |
          source ../.venv/bin/activate
          set -e
          laktory preview
        working-directory: ${{ env.CWD }}

      - name: laktory deploy
        if: ${{ inputs.action == 'deploy' }}
        run: |
          source ../.venv/bin/activate
          laktory deploy -y
        working-directory: ${{ env.CWD }}

      - name: laktory destroy
        if: ${{ inputs.action == 'destroy' }}
        run: |
          source ../.venv/bin/activate
          laktory destroy -y
        working-directory: ${{ env.CWD }}

      - name: laktory run job
        if: ${{ inputs.action == 'run-job' }}
        run: |
          source ../.venv/bin/activate
          laktory run --dbks-job ${{ inputs.resource_name }}
        working-directory: ${{ env.CWD }}

      - name: laktory run dlt
        if: ${{ inputs.action == 'run-dlt' }}
        run: |
          source ../.venv/bin/activate
          laktory run --dbks-pipeline ${{ inputs.resource_name }}
        working-directory: ${{ env.CWD }}
